version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crud"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ahwqtn21zlft"
s3_prefix = "crud"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
